# -*- mode: yaml; coding: utf-8 -*-

include:
    - project: qs/spin/spin_plugin_common
      ref: v1.7.1
      file: ci/.gitlab-ci.yml

# ------------------------------------------------------------------------------
test_linux:
    # Use an image that has node installed to test the node.use use-case.
    image: registry.contact.de/cetest:16.0-6.latest

triggered_integration_tests_linux:
    # Use an image that has node installed to test the node.use use-case.
    image: registry.contact.de/cetest:16.0-6.latest
    before_script:
        # We need to overwrite this, as spin_plugin_common needs to install jq and
        # asserts that we're root, which isn't the case for cetest. But as jq is
        # already installed, we can simply do the rest of spin_plugin_common's
        # before_script:
        - |
            export WHEEL_JOB_ID=$( \
              curl -s \
              "${CI_API_V4_URL}/projects/1065/pipelines/${PARENT_PIPELINE_ID}/jobs?scope=success" \
              | jq -S '.[] | select (.name == "wheel") | {id}' | jq -rj '.[]' \
            )
        - curl -O ${CI_API_V4_URL}/projects/1065/jobs/${WHEEL_JOB_ID}/artifacts.zip
        - unzip artifacts.zip "dist/*"
        - pip install dist/cs.spin*.whl
        - pip install --index-url https://packages.contact.de/tools/stable dist/cs.spin*.whl -r requirements-dev.txt
