# -*- mode: yaml; coding: utf-8 -*-

include:
    - project: qs/spin/spin_plugin_common
      ref: v1.3.0
      file: ci/.gitlab-ci.yml

# ------------------------------------------------------------------------------
test_linux:
    # Use an image that has node installed to the the node.use use-case.
    image: registry.contact.de/cetest:16.0-3.latest

# ------------------------------------------------------------------------------
# FIXME: The following customizations must be removed as soon as spin_frontend
#        provides a valid documentation
.release_deps:
    needs:
        - wheel
        - job: test_linux
          artifacts: false
        - job: test_windows
          artifacts: false

documentation:
    rules:
        - when: never

pages:
    rules:
        - when: never
