# -*- mode: yaml; coding: utf-8 -*-

include:
    - project: qs/spin/spin_plugin_common
      ref: v1.0.0
      file: ci/.gitlab-ci.yml

test_linux:
    # Use an image that has node installed to the the node.use use-case.
    image: registry.contact.de/cetest:16.0-2.latest
