# -*- mode: yaml; coding: utf-8 -*-

include:
    - project: qs/spin/spin_plugin_common
      ref: v1.0.1
      file: ci/.gitlab-ci.yml

# ------------------------------------------------------------------------------
test_linux:
    # FIXME: Remove custom before_script as soon as cs.spin is not installed as
    #        optional dependency in spin_plugin_common
    before_script:
        - pip install --index-url https://packages.contact.de/tools/stable -r requirements-dev.txt
    # Use an image that has node installed to the the node.use use-case.
    image: registry.contact.de/cetest:16.0-2.latest

# FIXME: The following workaround can be removed as soon as this commit is
#        released and used within this CI config.
#        https://code.contact.de/qs/spin/spin_plugin_common/-/merge_requests/6
test_windows:
    before_script:
        - python -m venv venv
        - venv\Scripts\activate.ps1
        - pip install --index-url https://packages.contact.de/tools/stable -r requirements-dev.txt
