# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
    os: ubuntu-24.04
    tools:
        python: '3.13'
    commands:
        # Upgrade needed due to dependency conflict with platformdirs (spin vs
        # virtualenv)
        # Create a dummy redis-server to satisfy csspin-ce dependency
        - mkdir -p bin
        - echo '#!/bin/sh\nexit 0' > bin/redis-server
        - ls bin
        - cat bin/redis-server
        - chmod +x ./bin/redis-server
        - export PATH="$PWD/bin:$PATH"
        - python -m pip install --upgrade virtualenv
        - python -m pip install csspin
        - spin -C . -f doc/spinfile.yaml provision
        - spin -C . -f doc/spinfile.yaml docs html
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - mv doc/_build/html/* $READTHEDOCS_OUTPUT/html
